[package]
name = "monkeysmash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
file = "1.1.2"
rand = "0.8.5"
sqlite = "0.30.4"
